# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: lineageos17.1
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/LineageOS/android_kernel_xiaomi_msm8998
          kernel-dir: xzr-4.9
          kernel-branch: lineage-17.1
          config: sagit_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
